---
# ansible-playbook -e "RANCHER_PROJECT_NAME=kube" -i provision/scaleworks provision/configure_host.yml
- hosts: "{{ RANCHER_PROJECT_NAME }}"
  become: true
  gather_facts: yes
  vars:
    additional_disks:
      - disk: /dev/sdb
        fstype: ext4
        mount_options: defaults
        mount: /data
    docker_opts: "-H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 --registry-mirror=http://thoughtworks.io:5000 --insecure-registry=thoughtworks.io:5000 --insecure-registry=thoughtworks.io:5001 --insecure-registry=thoughtworks.io:5002"
    docker_certs:
      - host: reg.dev.twleansw.com
        cert: reg.dev.twleansw.com.crt
    docker_registries:
      - host: "https://index.docker.io/v1/"
        auth: "Zmx5MndpbmQ6cHdjNTAycg=="
        email: "fly2wind@gmail.com"
      - host: "http://thoughtworks.io:5000/"
        auth: "Zmx5MndpbmQ6cHdjNTAycg=="
        email: "fly2wind@gmail.com"
      - host: "reg.dev.twleansw.com"
        auth: "YWRtaW46TGVhbnN3ZGV2MQ=="
        email: "admin@admin.com"
    docker_additonal_directory: /data/lib/docker
  roles:
    - common
    - docker
