---
# ansible-playbook -i provision/scaleworks provision/configure_repos.yml
- hosts: repository
  gather_facts: yes
  vars:
    certs_data_dir: "{{ inventory_dir }}/files"
    gogs_web_port: 3000
    gogs_ssh_port: 10022
    gogs_data_dir: /data/lib/gogs
    nexus_port: 8081
    nexus_data_dir: "/data/lib/nexus"
    nexus_local_users:
      - username: fly2wind
        first_name: Docker
        last_name: User
        email: fly2wind@gmail.com
        password: pwc502r
        roles:
          - nx-admin
    nginx_vhosts:
      - listen: "80"
        server_name: "repo.thoughtworks.io"
        ssl: false
        extra_parameters: |
          location / {
            proxy_pass http://repo;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
      - listen: "443"
        server_name: "thoughtworks.io"
        ssl: true
        ssl_certificate: /etc/nginx/ssl/thoughtworks.pem
        ssl_certificate_key: /etc/nginx/ssl/thoughtworks.key
        extra_parameters: |
          location / {
            proxy_pass http://registry;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
      - listen: "443"
        server_name: "repo.thoughtworks.io"
        ssl: true
        ssl_certificate: /etc/nginx/ssl/thoughtworks.pem
        ssl_certificate_key: /etc/nginx/ssl/thoughtworks.key
        extra_parameters: |
          location / {
            proxy_pass http://repo;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
      - listen: "80"
        server_name: "git.thoughtworks.io"
        ssl: false
        extra_parameters: |
          location / {
            proxy_pass http://git;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
    nginx_upstreams:
      - name: repo
        servers:
          - "{{ hostvars[groups['repository'][0]]['ansible_host'] }}:{{ nexus_port }}"
      - name: registry
        servers:
          - "{{ hostvars[groups['repository'][0]]['ansible_host'] }}:5000"
      - name: git
        servers:
          - "{{ hostvars[groups['repository'][0]]['ansible_host'] }}:{{ gogs_web_port }}"
  pre_tasks:
    - name: ensure nginx ssl directory
      file:
        path: "/etc/nginx/ssl"
        state: directory
        owner: root
        group: root
      become: yes
    - name: copy certs
      copy:
        src: "{{ certs_data_dir }}/{{ item }}"
        dest: "/etc/nginx/ssl/{{ item }}"
      with_items:
        - thoughtworks.key
        - thoughtworks.pem
      become: true
  roles:
    - gogs
    - nexus
    - nginx
