---
# ansible-playbook -i provision/scaleworks provision/configure_masters.yml
- hosts: common
  become: false
  gather_facts: yes
  roles:
    - rancher-nginx

- hosts: masters
  become: true
  gather_facts: yes
  vars:
    etcd_data_dir: /data/lib/etcd
  roles:
    - etcd
    - rancher
