---
- name: clean nginx configuration
  file:
    path: /etc/nginx/conf
    state: absent
  become: yes

- name: ensure nginx directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - /etc/nginx/ssl
    - /etc/nginx/conf
  become: yes

- name: generate nginx configuration
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
  become: yes

- name: generate vhost configuration
  template:
    src: vhost.conf.j2
    dest: "/etc/nginx/conf/{{ item.server_name.split(' ')[0] }}_{{ item.listen }}.conf"
  with_items: "{{ nginx_vhosts }}"
  become: yes

- name: start nginx container
  docker_container:
    name: "nginx"
    image: "nginx"
    network_mode: host
    volumes:
      - "/etc/nginx/ssl:/etc/nginx/ssl:ro"
      - "/etc/nginx/conf:/etc/nginx/conf:ro"
      - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    restart_policy: unless-stopped
  become: yes
