---
- name: remove nginx configuration
  file:
    path: /etc/nginx/conf.d
    state: absent
  become: yes

- name: ensure nginx configuration directory
  file:
    path: "/etc/nginx/conf.d"
    state: directory
    owner: root
    group: root
  become: yes

- name: generate nginx configuration
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
  become: yes

- name: generate vhost configuration
  template:
    src: vhost.conf.j2
    dest: "/etc/nginx/conf.d/{{ item.server_name.split(' ')[0] }}_{{ item.listen }}.conf"
  with_items: "{{ nginx_vhosts }}"
  become: yes

- name: start nginx container
  docker_container:
    name: "nginx"
    image: "nginx:stable"
    network_mode: host
    volumes:
      - "/etc/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    restart_policy: unless-stopped
  become: yes
