---




# configs
nginx_worker_processes: "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
nginx_worker_connections: "1024"

nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_log_format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'

nginx_vhosts:
  - listen: "80"
    server_name: "localhost"
    root: "/usr/share/nginx/html"
    index: "index.html index.htm"

nginx_upstreams: []
