---
- name: wait for the rancher server to start
  uri:
    url: "http://{{ RANCHER_MASTER_HOST }}:{{ RANCHER_MASTER_PORT }}/v1"
    status_code: 200,401
  become: no
  run_once: yes
  delegate_to: localhost
  register: rancher_auth
  until: rancher_auth.status == 200 or rancher_auth.status == 401
  retries: 5
  delay: 30

- debug: msg="{{ RANCHER_APIKEY_PUBLIC }}"

- debug: msg="{{ RANCHER_APIKEY_SECRET }}"

- name: config apikey
  uri:
    method: POST
    url: "http://{{ RANCHER_MASTER_HOST }}:{{ RANCHER_MASTER_PORT }}/v1/apikeys"
    body: "{{ rancher_apikeys_body | to_json }}"
    body_format: json
    status_code: 201
  become: no
  run_once: yes
  delegate_to: localhost
  ignore_errors: true
  when: rancher_auth.status == 200
  delay: 10

- name: config ldap authentication
  uri:
    method: POST
    url: "http://{{ RANCHER_MASTER_HOST }}:{{ RANCHER_MASTER_PORT }}/v1/openldapconfigs"
    user:     "{{ RANCHER_APIKEY_PUBLIC }}"
    password: "{{ RANCHER_APIKEY_SECRET }}"
    body: "{{ rancher_openldap_body | to_json }}"
    body_format: json
    status_code: 201
  become: no
  run_once: yes
  delegate_to: localhost
  when: rancher_auth.status == 200
  delay: 10

- name: config admin user
  uri:
    method: PUT
    url: "http://{{ RANCHER_MASTER_HOST }}:{{ RANCHER_MASTER_PORT }}/v1/accounts/1a1"
    user:     "{{ RANCHER_APIKEY_PUBLIC }}"
    password: "{{ RANCHER_APIKEY_SECRET }}"
    body: "{{ rancher_admins_body | to_json }}"
    body_format: json
    status_code: 200
  become: no
  run_once: yes
  delegate_to: localhost
  when: rancher_auth.status == 200
  delay: 10

#- name: config catalogs
#  uri:
#      method: PUT
#      url: "http://{{ RANCHER_MASTER_HOST }}:{{ RANCHER_MASTER_PORT }}/v1/settings/catalog.url"
#      user:     "{{ RANCHER_APIKEY_PUBLIC }}"
#      password: "{{ RANCHER_APIKEY_SECRET }}"
#      body: "{{ rancher_catalogs_body | to_json }}"
#      body_format: json
#      status_code: 200
#  become: no
#  run_once: yes
#  delegate_to: localhost
#  delay: 10
