---
rancher_jenkins_plugins:
  - git
  - subversion
  - workflow-aggregator
  - dashboard-view
  - cloudbees-folder
  - token-macro
  - simple-theme
  - docker
  - ldap
  - locale
  - swarm
rancher_jenkins_config:
  security:
    ldap:
      server: "ldap://{{ LDAP_HOST }}:{{ LDAP_PORT }}"
      rootDN: "{{ LDAP_BASE_DN }}"
      userSearchBase: "{{ LDAP_USER_SEARCH_BASE }}"
      userSearchFilter: "{{ LDAP_USER_SEARCH_FILTER }}"
      groupSearchBase: "{{ LDAP_GROUP_SEARCH_BASE }}"
      groupSearchFilter: "{{ LDAP_HROUP_SEARCH_FILTER }}"
      groupSearchAttr: memberOf
      managerDN: "{{ LDAP_BIND_DN }}"
      managerPassword: "{{ LDAP_BIND_ENCRYPT }}"
  credentials:
  - id: jenkins-slave-password
    description: Jenkis Slave with Password Configuration
    username: root
    password: jenkins
  cloud:
    docker:
    - name: toc-infra01
      serverUrl: tcp://10.202.128.112:2375
      containerCap: '50'
      connectTimeout: 5
      readTimeout: 15
      credentialsId: jenkins-slave-password
      templates:
      - image: baselibrary/jenkins-slave:1.12
        command: "/usr/sbin/sshd -D"
        volumes: "/var/run/docker.sock:/var/run/docker.sock\n /data/lib/jenkins:/data/lib/jenkins\n /tmp:/tmp"
        volumesFrom: ''
        environments: SSH_PASS=jenkins
        bindAllPorts: false
        privileged: false
        tty: false
        label: docker
        remoteFs: "/data/lib/jenkins"
        remoteFsMapping: "/data/lib/jenkins"
        instanceCap: '2'
        numExecutors: 1
        removeVolume: false
        pullStrategy: Pull once and update latest
    - name: toc-infra02
      serverUrl: tcp://10.202.128.113:2375
      containerCap: '50'
      connectTimeout: 5
      readTimeout: 15
      credentialsId: jenkins-slave-password
      templates:
      - image: baselibrary/jenkins-slave:1.12
        command: "/usr/sbin/sshd -D"
        volumes: "/var/run/docker.sock:/var/run/docker.sock\n /data/lib/jenkins:/data/lib/jenkins\n /tmp:/tmp"
        volumesFrom: ''
        environments: SSH_PASS=jenkins
        bindAllPorts: false
        privileged: false
        tty: false
        label: docker
        remoteFs: "/data/lib/jenkins"
        remoteFsMapping: "/data/lib/jenkins"
        instanceCap: '2'
        numExecutors: 1
        removeVolume: false
        pullStrategy: Pull once and update latest
    - name: toc-infra03
      serverUrl: tcp://10.202.128.114:2375
      containerCap: '50'
      connectTimeout: 5
      readTimeout: 15
      credentialsId: jenkins-slave-password
      templates:
      - image: baselibrary/jenkins-slave:1.12
        command: "/usr/sbin/sshd -D"
        volumes: "/var/run/docker.sock:/var/run/docker.sock\n /data/lib/jenkins:/data/lib/jenkins\n /tmp:/tmp"
        volumesFrom: ''
        environments: SSH_PASS=jenkins
        bindAllPorts: false
        privileged: false
        tty: false
        label: docker
        remoteFs: "/data/lib/jenkins"
        remoteFsMapping: "/data/lib/jenkins"
        instanceCap: '2'
        numExecutors: 1
        removeVolume: false
        pullStrategy: Pull once and update latest
